import { BaseConfig } from './BaseConfig'

export class BubblesCfg extends BaseConfig {
    bubbleCantDo: string = ''
    bubbleIdle: string = ''
    bubbleCollectCrystal: string = ''
    bubbleCollectOre: string = ''
    bubbleCollectStud: string = ''
    bubbleCollectDynamite: string = ''
    bubbleCollectBarrier: string = ''
    bubbleCollectElecFence: string = ''
    bubbleCollectDrill: string = ''
    bubbleCollectSpade: string = ''
    bubbleCollectHammer: string = ''
    bubbleCollectSpanner: string = ''
    bubbleCollectLaser: string = ''
    bubbleCollectPusher: string = ''
    bubbleCollectFreezer: string = ''
    bubbleCollectBirdScarer: string = ''
    bubbleCarryCrystal: string = ''
    bubbleCarryOre: string = ''
    bubbleCarryStud: string = ''
    bubbleCarryDynamite: string = ''
    bubbleCarryBarrier: string = ''
    bubbleCarryElecFence: string = ''
    bubbleGoto: string = ''
    bubbleDynamite: string = ''
    bubbleReinforce: string = ''
    bubbleDrill: string = ''
    bubbleRepair: string = ''
    bubbleDig: string = ''
    bubbleFlee: string = ''
    bubblePowerOff: string = ''
    bubbleCallToArms: string = ''
    bubbleElecFence: string = ''
    bubbleEat: string = ''
    bubbleDrive: string = ''
    bubbleUpgrade: string = ''
    bubbleBuildPath: string = ''
    bubbleTrain: string = ''
    bubbleRecharge: string = ''
    bubbleRequest: string = ''
}
