import { BaseConfig } from './BaseConfig'

export type Cursor = keyof PointerCfg

export class PointerCfg extends BaseConfig {
    pointerBlank: string = ''
    pointerStandard: string = ''
    pointerDrill: string = ''
    pointerCantDrill: string = ''
    pointerClear: string = ''
    pointerGo: string = ''
    pointerCantGo: string = ''
    pointerTeleport: string = ''
    pointerCantTeleport: string = ''
    pointerReinforce: string = ''
    pointerCantReinforce: string = ''
    pointerSelected: string = ''
    pointerRadarPan: string = ''
    pointerTrackObject: string = ''
    pointerZoom: string = ''
    pointerCantZoom: string = ''
    pointerHelp: string = ''
    pointerCantHelp: string = ''
    pointerPutDown: string = ''
    pointerGetIn: string = ''
    pointerGetOut: string = ''
    pointerOkay: string = ''
    pointerNotOkay: string = ''
    pointerCanBuild: string = ''
    pointerCannotBuild: string = ''
    pointerDynamite: string = ''
    pointerCantDynamite: string = ''
    pointerPickUp: string = ''
    pointerCantPickUp: string = ''
    pointerPickUpOre: string = ''
    pointerLegoManCantDig: string = ''
    pointerVehicleCantDig: string = ''
    pointerLegoManDig: string = ''
    pointerVehicleDig: string = ''
    pointerLegoManCantPickUp: string = ''
    pointerVehicleCantPickUp: string = ''
    pointerLegoManPickUp: string = ''
    pointerVehiclePickUp: string = ''
    pointerLegoManCantGo: string = ''
    pointerVehicleCantGo: string = ''
    pointerLegoManGo: string = ''
    pointerVehicleGo: string = ''
    pointerLegoManClear: string = ''
    pointerVehicleClear: string = ''
    pointerSurfaceTypeImmovable: string = ''
    pointerSurfaceTypeHard: string = ''
    pointerSurfaceTypeMedium: string = ''
    pointerSurfaceTypeLoose: string = ''
    pointerSurfaceTypeSoil: string = ''
    pointerSurfaceTypeOreSeam: string = ''
    pointerSurfaceTypeCrystalSeam: string = ''
    pointerSurfaceTypeRechargeSeam: string = ''
}
