language: node_js
node_js:
  - 'stable'
cache:
  yarn: true
  directories:
    - dist
    - .cache
script:
  - npm run prod
branches:
  only:
    - master

deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep built pages
  skip-cleanup: true
  # Directory where your generated files are located
  local_dir: dist
  # GitHub's security/auth token
  github-token: $GITHUB_TOKEN
  # Git branch on which it should deploy (master, gh-pages, foo...)
  target_branch: gh-pages
  on:
    # Which branch on commit/push will trigger deployment
    branch: master
