// noinspection JSUnusedGlobalSymbols
export enum Sample {
    SFX_Bodge,

    SFX_Drip,

    SFX_Drill,
    SFX_DrillFade,
    SFX_RockBreak,
    SFX_FallIn,

    SFX_RockMonster,
    SFX_RockMonster2,
    SFX_Ambient,
    SFX_Ambientloop,

    SFX_ButtonPressed,
    SFX_Radar,
    SFX_Siren,
    SFX_CrystalRecharge,
    SFX_Laser,
    SFX_LaserHit,
    SFX_LazerRecharge,
    SFX_TopPriority,
    SFX_ImmovableRock,
    SFX_Wall,
    SFX_Floor,
    SFX_BoulderHit,
    SFX_Lava,

    SFX_Okay,
    SFX_NotOkay,

    SFX_RockWipe,
    SFX_CaptainSlide,
    SFX_Dynamite,

    SFX_PlaceCrystal,
    SFX_PlaceOre,
    SFX_Place,

    SND_Landslide,
    SND_CRserv1,
    SND_CRserv2,
    SND_Refine,
    SND_Docksload,
    SND_Docksunload,
    SND_Drop,
    SND_upgradelc1,
    SND_Explode1,
    SND_Explode2,
    SND_Rumble,

    SND_RMGrunt,
    SND_RMstomp,
    SND_RMrokstep,
    SND_RMrokslid,
    SND_RMsoftstep,
    SND_RMcrack,
    SND_RMbigrok,
    SND_RMsmalrock,
    SND_RMroar1,
    SND_RMroar2,
    SND_RMfootbreak,
    SND_RMfistbreak,
    SND_RMscoop,
    SND_RMswipe,
    SND_RMCrumble,
    SND_RMImpact,
    SND_RMeat1,
    SND_RMeat2,
    SND_RMeat3,
    SND_Snore,
    SND_RMEAT,
    SND_RMREST,
    SND_RMhurl,

    SND_SLUGIN,
    SND_SLUGOUT,
    SND_Sonic,
    SND_SUCK,

    SND_teleport,
    SND_BARRIERplace,
    SND_BARRIERwood,
    SND_elecy,
    SND_starttel,
    SND_plazsmall,
    SND_plazlarg,
    SND_BTHUD,

    SND_SHAKE,
    SND_Slipup,
    SND_bump,
    SND_Groan,
    SND_hupp,
    SND_haaa,
    SND_PANTS,

    SND_dump,
    SND_land,
    SND_chuck,
    SND_deposit,
    SND_dig,
    SND_hammer,
    SND_dynamite,
    SND_screw1,
    SND_screw2,
    SND_screw3,

    SND_pilotdrill,
    SND_Pilotdrillfade,
    SND_TeleUp,
    SND_LASER,

    SND_Hurt,
    SND_Yippee,
    SND_Panic,

    SND_AirBeat,

    SND_WALKER1,
    SND_WALKER2,
    SND_WALKER3,
    SND_WALKDRILL,
    SND_WALKDRILLFADE,

    SND_SHOVEL,
    SND_SMACK,

    SND_BIGDIGDRILL,
    SND_BIGDIGDRILLFADE,

    SND_Bsplosh,
    SND_Ssplosh,

//     Stream_Objective_Levels::Level01,
//     Stream_Objective_Levels::Level02,
//     Stream_Objective_Levels::Level03,
//     Stream_Objective_Levels::Level04,
//     Stream_Objective_Levels::Level05,
//     Stream_Objective_Levels::Level06,
//     Stream_Objective_Levels::Level07,
//     Stream_Objective_Levels::Level08,
//     Stream_Objective_Levels::Level09,
//     Stream_Objective_Levels::Level10,
//     Stream_Objective_Levels::Level11,
//     Stream_Objective_Levels::Level12,
//     Stream_Objective_Levels::Level13,
//     Stream_Objective_Levels::Level14,
//     Stream_Objective_Levels::Level15,
//     Stream_Objective_Levels::Level16,
//     Stream_Objective_Levels::Level17,
//     Stream_Objective_Levels::Level18,
//     Stream_Objective_Levels::Level19,
//     Stream_Objective_Levels::Level20,
//     Stream_Objective_Levels::Level21,
//     Stream_Objective_Levels::Level22,
//     Stream_Objective_Levels::Level23,
//     Stream_Objective_Levels::Level24,
//     Stream_Objective_Levels::Level25,
//
//     Stream_Objective_Levels::DigTuto_01,
//     Stream_Objective_Levels::DigTuto_02,
//     Stream_Objective_Levels::DigTuto_03,
//     Stream_Objective_Levels::MoveTuto_01,
//     Stream_Objective_Levels::MoveTuto_02,
//     Stream_Objective_Levels::BuildTuto_01,
//     Stream_Objective_Levels::BuildTuto_01,
//     Stream_Objective_Levels::DefenceTuto_01,
//
// Stream_Objective_Levels::Tutorial02,
//     Stream_Objective_Levels::Tutorial05,
//     Stream_Objective_Levels::Tutorial07,
//     Stream_Objective_Levels::Tutorial01,
//     Stream_Objective_Levels::Tutorial04,
//     Stream_Objective_Levels::Tutorial03,
//     Stream_Objective_Levels::Tutorial06,
//     Stream_Objective_Levels::Tutorial08,
//
//     Stream_ObjectiveFailed_Levels::Level01,
//     Stream_ObjectiveFailed_Levels::Level02,
//     Stream_ObjectiveFailed_Levels::Level03,
//     Stream_ObjectiveFailed_Levels::Level04,
//     Stream_ObjectiveFailed_Levels::Level05,
//     Stream_ObjectiveFailed_Levels::Level06,
//     Stream_ObjectiveFailed_Levels::Level07,
//     Stream_ObjectiveFailed_Levels::Level08,
//     Stream_ObjectiveFailed_Levels::Level09,
//     Stream_ObjectiveFailed_Levels::Level10,
//     Stream_ObjectiveFailed_Levels::Level11,
//     Stream_ObjectiveFailed_Levels::Level12,
//     Stream_ObjectiveFailed_Levels::Level13,
//     Stream_ObjectiveFailed_Levels::Level14,
//     Stream_ObjectiveFailed_Levels::Level15,
//     Stream_ObjectiveFailed_Levels::Level16,
//     Stream_ObjectiveFailed_Levels::Level17,
//     Stream_ObjectiveFailed_Levels::Level18,
//     Stream_ObjectiveFailed_Levels::Level19,
//     Stream_ObjectiveFailed_Levels::Level20,
//     Stream_ObjectiveFailed_Levels::Level21,
//     Stream_ObjectiveFailed_Levels::Level22,
//     Stream_ObjectiveFailed_Levels::Level23,
//     Stream_ObjectiveFailed_Levels::Level24,
//     Stream_ObjectiveFailed_Levels::Level25,
//
//     Stream_ObjectiveAcheived_Levels::Level01,
//     Stream_ObjectiveAcheived_Levels::Level02,
//     Stream_ObjectiveAcheived_Levels::Level03,
//     Stream_ObjectiveAcheived_Levels::Level04,
//     Stream_ObjectiveAcheived_Levels::Level05,
//     Stream_ObjectiveAcheived_Levels::Level06,
//     Stream_ObjectiveAcheived_Levels::Level07,
//     Stream_ObjectiveAcheived_Levels::Level08,
//     Stream_ObjectiveAcheived_Levels::Level09,
//     Stream_ObjectiveAcheived_Levels::Level10,
//     Stream_ObjectiveAcheived_Levels::Level11,
//     Stream_ObjectiveAcheived_Levels::Level12,
//     Stream_ObjectiveAcheived_Levels::Level13,
//     Stream_ObjectiveAcheived_Levels::Level14,
//     Stream_ObjectiveAcheived_Levels::Level15,
//     Stream_ObjectiveAcheived_Levels::Level16,
//     Stream_ObjectiveAcheived_Levels::Level17,
//     Stream_ObjectiveAcheived_Levels::Level18,
//     Stream_ObjectiveAcheived_Levels::Level19,
//     Stream_ObjectiveAcheived_Levels::Level20,
//     Stream_ObjectiveAcheived_Levels::Level21,
//     Stream_ObjectiveAcheived_Levels::Level22,
//     Stream_ObjectiveAcheived_Levels::Level23,
//     Stream_ObjectiveAcheived_Levels::Level24,
//     Stream_ObjectiveAcheived_Levels::Level25,
//
//     Stream_ObjectiveAcheived_Levels::DigTuto_01,
//     Stream_ObjectiveAcheived_Levels::DigTuto_02,
//     Stream_ObjectiveAcheived_Levels::DigTuto_03,
//     Stream_ObjectiveAcheived_Levels::MoveTuto_01,
//     Stream_ObjectiveAcheived_Levels::MoveTuto_02,
//     Stream_ObjectiveAcheived_Levels::BuildTuto_01,
//     Stream_ObjectiveAcheived_Levels::BuildTuto_01,
//     Stream_ObjectiveAcheived_Levels::DefenceTuto_01,
//
//     Stream_ObjectiveAcheived_Levels::Tutorial02,
//     Stream_ObjectiveAcheived_Levels::Tutorial05,
//     Stream_ObjectiveAcheived_Levels::Tutorial07,
//     Stream_ObjectiveAcheived_Levels::Tutorial01,
//     Stream_ObjectiveAcheived_Levels::Tutorial04 ,
//     Stream_ObjectiveAcheived_Levels::Tutorial03,
//     Stream_ObjectiveAcheived_Levels::Tutorial06,
//     Stream_ObjectiveAcheived_Levels::Tutorial08,

    Stream_ObjectiveFailedCrystals,

    Stream_LevelName_Level1,
    Stream_LevelName_Level2,
    Stream_LevelName_Level3,
    Stream_LevelName_Level4,
    Stream_LevelName_Level5,
    Stream_LevelName_Level6,
    Stream_LevelName_Level7,
    Stream_LevelName_Level8,
    Stream_LevelName_Level9,
    Stream_LevelName_Level10,
    Stream_LevelName_Level11,
    Stream_LevelName_Level12,
    Stream_LevelName_Level13,
    Stream_LevelName_Level14,
    Stream_LevelName_Level15,
    Stream_LevelName_Level16,
    Stream_LevelName_Level17,
    Stream_LevelName_Level18,
    Stream_LevelName_Level19,
    Stream_LevelName_Level20,
    Stream_LevelName_Level21,
    Stream_LevelName_Level22,
    Stream_LevelName_Level23,
    Stream_LevelName_Level24,
    Stream_LevelName_Level25,
    Stream_LevelName_TLevel1,
    Stream_LevelName_TLevel2,
    Stream_LevelName_TLevel3,
    Stream_LevelName_TLevel4,
    Stream_LevelName_TLevel5,
    Stream_LevelName_TLevel6,
    Stream_LevelName_TLevel7,
    Stream_LevelName_TLevel8,

    SND_SmallEngine,
    SND_MediumEngine,
    SND_LargeEngine,
    SND_HeliEngine,
    SND_Catamaran,

    SND_PowerBuildingHum,
    SND_BuildingHum,

    ObjSFX_Hoverboard,
    ObjSFX_SmallDigger,
    ObjSFX_SmallTruck,
    ObjSFX_SmallCat,
    ObjSFX_SmallMLP,
    ObjSFX_SmallHeli,
    ObjSFX_BullDozer,
    ObjSFX_WalkerDigger,
    ObjSFX_LargeMLP,
    ObjSFX_LargeDigger,
    ObjSFX_LargeCat,
    ObjSFX_LargeHeli,

    ObjSFX_Pilot,

    ObjSFX_RockMonster,

    ObjSFX_SmallSpider,

    ObjSFX_Slug,
    ObjSFX_LavaMonster,
    ObjSFX_IceMonster,

    ObjSFX_Toolstation,
    ObjSFX_TeleportPad,
    ObjSFX_Docks,
    ObjSFX_Powerstation,
    ObjSFX_Barracks,
    ObjSFX_Upgrade,
    ObjSFX_Geodome,
    ObjSFX_OreRefinery,
    ObjSFX_Gunstation,
    ObjSFX_TeleportBIG,

    ObjSFX_Crystal,
    ObjSFX_Ore,
    ObjSFX_Stud,

    TTSFX_Radar,
    TTSFX_TrackObject,
    TTSFX_MapView,
    TTSFX_ActionStations,
    TTSFX_Priorities,
    TTSFX_PriorityDisable,
    TTSFX_IncreasePrioirity,
    TTSFX_ZoomIn,
    TTSFX_ZoomOut,
    TTSFX_RotateMap,
    TTSFX_Goto,
    TTSFX_Options,
    TTSFX_Back,
    TTSFX_ResetPrioirities,

    IntSFX_TeleRR,
    IntSFX_NoTeleRR,
    IntSFX_Buildings,
    IntSFX_SmallVehicles,
    IntSFX_LargeVehicles,
    IntSFX_Path,
    IntSFX_NoPath,
    IntSFX_Rubble,
    IntSFX_NoRubble,
    IntSFX_SellRR,
    IntSFX_UnloadVehicle,
    IntSFX_NoUnloadVehicle,
    IntSFX_Drop,
    IntSFX_PickUp,
    IntSFX_NoPickUp,
    IntSFX_LoadVehicle,
    IntSFX_NoLoadVehicle,
    IntSFX_GetOut,
    IntSFX_NoGetOut,
    IntSFX_GetDriver,
    IntSFX_NoGetDriver,
    IntSFX_DrillWall,
    IntSFX_NoDrillWall,
    IntSFX_Reinforce,
    IntSFX_NoReinforce,
    IntSFX_Dynamite,
    IntSFX_NoDynamite,
    IntSFX_Upgrade,
    IntSFX_NoUpgrade,
    IntSFX_EyeView,
    IntSFX_NoEyeView,
    IntSFX_ShoulderView,
    IntSFX_NoShoulderView,
    IntSFX_PowerOn,
    IntSFX_PowerOff,
    IntSFX_NoPowerOff,
    IntSFX_UpgradeBuilding,
    IntSFX_NoUpgradeBuilding,
    IntSFX_RepairBuilding,
    IntSFX_NoRepairBuilding,
    IntSFX_TopView,
    IntSFX_CancelDrill,
    IntSFX_NoCancelDrill,
    IntSFX_ElecFence,
    IntSFX_NoElecFence,
    IntSFX_CancelBuilding,
    IntSFX_RemovePath,
    IntSFX_NoRemovePath,
    IntSFX_RemoveFence,
    IntSFX_SellVehicle,
    IntSFX_SellBuilding,
    IntSFX_DropSonic,
    IntSFX_ToolMenu,
    IntSFX_NoToolMenu,
    IntSFX_GetDrill,
    IntSFX_NoGetDrill,
    IntSFX_GetShovel,
    IntSFX_NoGetShovel,
    IntSFX_GetHammer,
    IntSFX_NoGetHammer,
    IntSFX_GetSpanner,
    IntSFX_NoGetSpanner,
    IntSFX_GetFreezer,
    IntSFX_NoGetFreezer,
    IntSFX_GetLaser,
    IntSFX_NoGetLaser,
    IntSFX_GetPusher,
    IntSFX_NoGetPusher,
    IntSFX_GetSonic,
    IntSFX_NoGetSonic,
    IntSFX_TrainMenu,
    IntSFX_NoTrainMenu,
    IntSFX_TrainDriver,
    IntSFX_NoTrainDriver,
    IntSFX_TrainEngineer,
    IntSFX_NoTrainEngineer,
    IntSFX_TrainGeologist,
    IntSFX_NoTrainGeologist,
    IntSFX_TrainPilot,
    IntSFX_NoTrainPilot,
    IntSFX_TrainSailor,
    IntSFX_NoTrainSailor,
    IntSFX_UpgradeVehicle,
    IntSFX_NoUpgradeVehicle,
    IntSFX_UpgradeEngine,
    IntSFX_NoUpgradeEngine,
    IntSFX_UpgradeDrill,
    IntSFX_NoUpgradeDrill,
    IntSFX_UpgradeScan,
    IntSFX_NoUpgradeScan,
    IntSFX_UpgradeCarry,
    IntSFX_NoUpgradeCarry,
    IntSFX_FeedRockRaiders,
    IntSFX_TrainExplosives,
    IntSFX_NoTrainExplosives,
    IntSFX_NoFeed,
    IntSFX_NoDropSonic,

    InfoSFX_AirLow,
    InfoSFX_AirOut,
    InfoSFX_CrystalsFound,
    InfoSFX_UnderAttack,
    InfoSFX_NewCavern,
    InfoSFX_PowerDrain,
    InfoSFX_Slug,
    InfoSFX_FoundRR,
    InfoSFX_Death,
    InfoSFX_Landslide,
    InfoSFX_Monster,

    SurfaceSFX_Immovable,
    SurfaceSFX_Hard,
    SurfaceSFX_Medium,
    SurfaceSFX_Loose,
    SurfaceSFX_Lava,
    SurfaceSFX_OreSeam,
    SurfaceSFX_Lake,
    SurfaceSFX_CrystalSeam,
    SurfaceSFX_RechargeSeam,
    SurfaceSFX_Rubble,
    SurfaceSFX_Reinforcement,
    SurfaceSFX_Path,
    SurfaceSFX_SlugHole,
    SurfaceSFX_Building,
    SurfaceSFX_Undiscovered,
    SurfaceSFX_Cavern,

    PriSFX_Drive,
    PriSFX_Crystals,
    PriSFX_Ore,
    PriSFX_Repair,
    PriSFX_Construction,
    PriSFX_Reinforce,
    PriSFX_Recharge,
    PriSFX_Drilling,

    DrillSFX_Grinder,
    DrillSFX_GrinderFade,

    SFX_MusicLoop,
    SFX_AmbientMusicLoop,
}
