export enum EventKey {

    SELECTED_SURFACE,
    SELECTED_BUILDING,
    SELECTED_RAIDER,
    SELECTED_VEHICLE,

    DESELECTED_ENTITY,

    JOB_CREATE,
    JOB_DELETE,

    RAIDER_REQUESTED,

    MATERIAL_AMOUNT_CHANGED,

    SPAWN_DYNAMITE,

    ENTITY_ADDED,
    ENTITY_REMOVED,

    CAVERN_DISCOVERED,

    ORE_FOUND,

    BUILDING_UPGRADED,

    RAIDER_TRAINED,

    LOCATION_DEATH,
    LOCATION_MONSTER,
    LOCATION_CRYSTAL_FOUND,
    LOCATION_UNDER_ATTACK,
    LOCATION_LANDSLIDE,
    LOCATION_POWER_DRAIN,
    LOCATION_SLUG_EMERGE,
    LOCATION_RAIDER_DISCOVERED,

}
